
box_settings:
  name:
  sn:
  vender:
  mac:

server:
  host: server.ismart.com
  port: 23409


probe_list:
  - name: ''
    enable: true
    handler:
      class: 'handlers.concox_gt03.DataAdapter'
      device_type: 'gt03'
      sequence_key: 'blue_earth.device.sequence.gt03'
      command_controller: 'mantis.BlueEarth.vendor.concox.gt03.command.CommandController'
